"""Auto-generated migration.

Revision ID: 37eea7e230cf
Revises: b8bdfff29b60
Create Date: 2026-06-24 20:07:02.916252
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37eea7e230cf'
down_revision = 'b8bdfff29b60'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
